api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('v1/', views.api, name='api'),   
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('accounts/signup', views.signup, name='signup'),
    path('accounts/login/', views.MyLoginView.as_view(), name='login'),
    
    path('restaurant/', views.RestaurantList.as_view(), name='restaurant_list'),
    path('restaurant/<int:pk>/', views.RestaurantDetail.as_view(), name='restaurant_detail'),
    path('restaurant/create/', views.RestaurantCreate.as_view(), name='restaurant_create'),
    path('restaurant/<int:pk>/update/', views.RestaurantUpdate.as_view(), name='restaurant_update'),
    path('restaurant/<int:pk>/delete/', views.RestaurantDelete.as_view(), name='restaurant_delete'),
    path('restaurant/<int:restaurant_id>/add_restaurant_photo/', views.add_restaurant_photo, name='add_restaurant_photo'),
    
    path('menu/<int:pk>/', views.MenuDetail.as_view(), name="menu_detail"),
    path('menu/<int:pk>/create/', views.MenuCreate.as_view(), name='menu_create'),      
    path('menu/<int:pk>/update', views.MenuUpdate.as_view(), name="menu_update"),
    path('menu/<int:pk>/delete', views.MenuDelete.as_view(), name="menu_delete"),
    path('menu/<int:menu_id>/add_menu_photo/<int:restaurant_id>/', views.add_menu_photo, name='add_menu_photo'),
    path('menu/<int:menu_id>/delete_menu_photo/<int:restaurant_id>/', views.delete_menu_photo, name='delete_menu_photo'),
    
    path('category/<int:pk>/create/', views.CategoryCreate.as_view(), name="category_create"),
    path('category/<int:pk>/update/<int:fk>/', views.CategoryUpdate.as_view(), name="category_update"),
    path('category/<int:pk>/delete/<int:fk>/', views.CategoryDelete.as_view(), name="category_delete"),
    
    path('food/<int:pk>/create/<int:fk>/', views.FoodCreate.as_view(), name='food_create'),          
    path('food/<int:pk>/update/<int:fk>/', views.FoodUpdate.as_view(), name='food_update'),          
    path('food/<int:pk>/delete/<int:fk>/', views.FoodDelete.as_view(), name='food_delete'),      
    path('food/<int:food_id>/add_food_photo/<int:menu_id>/', views.add_food_photo, name='add_food_photo'),
    path('food/<int:food_id>/delete_food_photo/<int:menu_id>/', views.delete_food_photo, name='delete_food_photo'),
    
    path('search/', views.search, name='search'),
]

navbar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Restaurant(models.Model):
    name = models.CharField(max_length=200, blank=False)
    address = models.CharField(max_length=100, blank=False)
    phone = models.CharField(max_length=100, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=300, blank=True, default='')
    zipcode = models.IntegerField(blank=False)
    date = models.DateTimeField(auto_now_add=True)
    restaurant_photo = models.CharField(max_length=300, default='https://s3-us-west-1.amazonaws.com/fishcollector/e5abd9.jpg')
    
    def __str__(self):
        return f'restaurant name - {self.name}'
    
    def get_absolute_url(self):
        return reverse('restaurant_detail', kwargs={'pk':self.id})

class Menu(models.Model):
    name = models.CharField(max_length=200, blank=False)
    description = models.TextField(max_length=500, blank=True, default='')
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    menu_photo = models.CharField(max_length=300, default='https://s3-us-west-1.amazonaws.com/fishcollector/e5abd9.jpg')
    date = models.DateTimeField(auto_now_add=True)    
    
    def __str__(self):
        return f'menu name - {self.name}'
    
    def get_absolute_url(self):
        return reverse('menu_detail', kwargs={'pk':self.id})

class Category(models.Model):
    name = models.CharField(max_length=200, blank=False)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'category name - {self.name}'

class Food(models.Model):
    name = models.CharField(max_length=200, blank=False)
    price = models.FloatField(blank=False)
    description = models.TextField(max_length=500, blank=True, default='')    
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    food_photo = models.CharField(max_length=300, default='https://s3-us-west-1.amazonaws.com/fishcollector/e5abd9.jpg')    
    
    def __str__(self):
        return f'food name - {self.name}'

main/forms.py
from django.forms import ModelForm
from .models import Restaurant

class RestaurantForm(ModelForm):
    class Meta:
        model = Restaurant
        fields = ['name', 'address', 'zipcode', 'phone', 'description']
        
        help_texts = {
            'name': ('Name of your restaurant'),
            'address': ('Please type in a correct address for your restaurant, eg: 225 Bush St, San Francisco, CA.'),
            'zipcode': ('Please type in your 5 digit zip code.'),            
            'phone': ('eg: 415-123-4567.'),
        }
        

main/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import Restaurant, Menu, Category, Food
from .forms import RestaurantForm
import uuid
import boto3
import os

SECRET_KEY='AIzaSyA5PFcm4YZ1KnBSQDyq-Eon2znBNuul95Q&'

def home(request):
    return render(
        request,
        'main/home.html',
    )
    
class Profile(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'user/profile.html'
    context_object_name = 'user'
    
    def get_context_data(self, **kwargs):
        user = User.objects.get(pk=self.kwargs['pk'])
        context = super().get_context_data(**kwargs)
        restaurants = user.restaurant_set.all().order_by('-date')
        MAP_BASE_URL='https://www.google.com/maps/embed/v1/place?key='+SECRET_KEY     
        context['restaurants'] = restaurants
        context['map'] = MAP_BASE_URL
        return context

class MyLoginView(LoginView):
    def get_success_url(self):
        user = self.request.user
        return reverse('profile', kwargs={'pk': user.id})        

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.first_name = request.POST.get("first_name")
            user.last_name = request.POST.get("last_name")
            user.email = request.POST.get("email")
            user.save()
            login(request, user)
            return redirect('profile', pk=user.id)
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)
    
class RestaurantList(ListView):
    model = Restaurant
    template_name = 'restaurant/restaurant_list.html'
    context_object_name = 'restaurants'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        restaurants = Restaurant.objects.all().order_by('-date')
        context['restaurants'] = restaurants
        MAP_BASE_URL='https://www.google.com/maps/embed/v1/place?key='+SECRET_KEY     
        context['map'] = MAP_BASE_URL
        return context
    
class RestaurantDetail(DetailView):
    model = Restaurant
    context_object_name = 'restaurant'
    template_name = 'restaurant/restaurant_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        restaurant = Restaurant.objects.get(pk=self.kwargs['pk']) 
        menus = restaurant.menu_set.all().order_by('-date')  
        MAP_BASE_URL='https://www.google.com/maps/embed/v1/place?key='+SECRET_KEY 
        context['map'] = MAP_BASE_URL
        context['menus'] = menus
        return context
    
class RestaurantCreate(LoginRequiredMixin, CreateView):
    model = Restaurant
    fields = ['name', 'address', 'phone', 'zipcode', 'description']
    template_name = 'restaurant/restaurant_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        restaurant_form = RestaurantForm()
        context = super().get_context_data(**kwargs)
        context['form'] = restaurant_form
        return context

class RestaurantUpdate(LoginRequiredMixin, UpdateView):
    model = Restaurant
    fields = ['name', 'address', 'phone', 'zipcode', 'description']
    template_name = 'restaurant/restaurant_form.html'
    
    def get_success_url(self):
        restaurant = Restaurant.objects.get(pk=self.kwargs['pk'])
        user = restaurant.user
        return reverse('profile', kwargs={'pk': user.id})
    
class RestaurantDelete(LoginRequiredMixin, DeleteView):
    model = Restaurant
    template_name = 'restaurant/restaurant_confirm_delete.html'
    
    def get_success_url(self):
        restaurant = Restaurant.objects.get(pk=self.kwargs['pk'])
        user = restaurant.user
        return reverse('profile', kwargs={'pk': user.id})
    
class MenuCreate(LoginRequiredMixin, CreateView):
    model = Menu
    fields = ['name', 'description']
    template_name = 'menu/menu_form.html'

    def form_valid(self, form):
        restaurant = Restaurant.objects.get(pk=self.kwargs['pk'])        
        form.instance.restaurant = restaurant
        return super().form_valid(form)
    
    def get_success_url(self):
        restaurant = Restaurant.objects.get(pk=self.kwargs['pk'])
        return reverse('restaurant_detail', kwargs={'pk': restaurant.id})

class MenuDetail(DetailView):
    model = Menu
    context_object_name = 'menu'
    template_name = 'menu/menu_detail.html'
    
    def get_context_data(self, **kwargs):
        menu = Menu.objects.get(pk=self.kwargs['pk'])
        restaurant = menu.restaurant
        menus = Menu.objects.filter(restaurant_id=restaurant.id).order_by('-date')
        context = super().get_context_data(**kwargs)
        context['restaurant'] = restaurant
        context['menus'] = menus
        return context

class MenuUpdate(LoginRequiredMixin, UpdateView):
    model = Menu
    context_object_name = 'menu'
    template_name = 'menu/menu_form.html'
    fields = ['name', 'description']

    def get_success_url(self):
        menu = Menu.objects.get(pk=self.kwargs['pk'])
        restaurant = menu.restaurant
        return reverse('restaurant_detail', kwargs={'pk': restaurant.id})

class MenuDelete(LoginRequiredMixin, DeleteView):
    model = Menu
    context_object_name = 'menu'
    template_name = "menu/menu_confirm_delete.html"

    def get_success_url(self):
        menu = Menu.objects.get(pk=self.kwargs['pk'])
        restaurant = menu.restaurant
        return reverse('restaurant_detail', kwargs={'pk': restaurant.id})

    def get_context_data(self, **kwargs):
        menu = Menu.objects.get(pk=self.kwargs['pk'])
        restaurant = menu.restaurant
        context = super().get_context_data(**kwargs)
        context['restaurant'] = restaurant
        return context

class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category 
    fields = ['name']
    template_name = 'categories/category_form.html'

    def form_valid(self, form):
        menu = Menu.objects.get(pk=self.kwargs['pk'])        
        form.instance.menu = menu 
        return super().form_valid(form)
    
    def get_success_url(self):
        menu = Menu.objects.get(pk=self.kwargs['pk'])
        return reverse('menu_detail', kwargs={'pk': menu.id})

class CategoryUpdate(LoginRequiredMixin, UpdateView):
    model = Category
    context_object_name = 'category'
    template_name = 'categories/category_form.html'
    fields = ['name']

    def get_success_url(self):
        menu = Menu.objects.get(pk=self.kwargs['fk'])
        return reverse('menu_detail', kwargs={'pk': menu.id})

class CategoryDelete(LoginRequiredMixin, DeleteView):
    model = Category
    context_object_name = 'category'
    template_name = 'categories/category_confirm_delete.html'

    def get_success_url(self):
        menu = Menu.objects.get(pk=self.kwargs['fk'])
        return reverse('menu_detail', kwargs={'pk': menu.id})

    def get_context_data(self, **kwargs):
        menu = Menu.objects.get(pk=self.kwargs['fk'])
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        return context

class FoodCreate(LoginRequiredMixin, CreateView):
    model = Food 
    fields = ['name', 'price', 'description']
    template_name = 'food/food_form.html'

    def form_valid(self, form):
        category = Category.objects.get(pk=self.kwargs['pk'])        
        form.instance.category = category 
        return super().form_valid(form)
    
    def get_success_url(self):
        menu = Menu.objects.get(pk=self.kwargs['fk'])
        return reverse('menu_detail', kwargs={'pk': menu.id})
    
class FoodUpdate(LoginRequiredMixin, UpdateView):
    model = Food
    context_object_name = 'food'
    template_name = 'food/food_form.html'
    fields = ['name', 'price', 'description']

    def get_success_url(self):
        menu = Menu.objects.get(pk=self.kwargs['fk'])
        return reverse('menu_detail', kwargs={'pk': menu.id})
    
class FoodDelete(LoginRequiredMixin, DeleteView):
    model = Food
    context_object_name = 'food'
    template_name = 'food/food_confirm_delete.html'

    def get_success_url(self):
        menu = Menu.objects.get(pk=self.kwargs['fk'])
        return reverse('menu_detail', kwargs={'pk': menu.id})

    def get_context_data(self, **kwargs):
        menu = Menu.objects.get(pk=self.kwargs['fk'])
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        return context
    
@login_required
def add_restaurant_photo(request, restaurant_id):
    photo_file = request.FILES.get('photo-file', None)
    restaurant = Restaurant.objects.get(id=restaurant_id)    
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            BUCKET = os.environ['BUCKET']
            S3_BASE_URL = os.environ['S3_BASE_URL']
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            restaurant.restaurant_photo = url
            restaurant.save()
        except:
            return
    return redirect(restaurant)

@login_required
def add_menu_photo(request, menu_id, restaurant_id):

main/templates/menu/menu_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="login">

	<h1>Delete Menu</h1>
	<h4>Are you sure you want to delete {{ object.name }}?</h4>
	<form action="" method="POST" class="container">
		{% csrf_token %}
		<button type="submit" class="btn btn-danger">Delete</button>
		<a href="{% url 'restaurant_detail' restaurant.id %}" class="btn btn-secondary">Cancel</a>
	</form>
</div>

{% endblock %}

main/templates/menu/menu_detail.html
{% extends 'main/base.html' %} {% load static %} {% block content %}

<ul class="nav nav-pills menu-header">
  {% for menu in menus %}
  <li class="nav-item">
    <a class="nav-link active mr-3" href="{% url 'menu_detail' menu.id %}"
      >{{ menu.name }}</a
    >
  </li>
  {% endfor %}
</ul>

<div class="row">
  <div class="col-2">
    <div
      class="nav flex-column nav-pills"
      id="v-pills-tab"
      role="tablist"
      aria-orientation="vertical"
    >
      {% if request.user == restaurant.user %}
      <a
        href="{% url 'category_create' menu.id %}"
        class="btn btn-outline-primary category-list"
        role="button"
        aria-pressed="true"
        >Add Category</a
      >
      {% endif %} {% for category in menu.category_set.all %}
      <div class="category-list">
        <a
          class="nav-link btn-outline-primary btn-lg"
          id="v-pills-home-tab"
          href="#{{category.name}}"
          aria-controls="v-pills-home"
          aria-selected="true"
          >{{category.name}}</a
        >
        {% if request.user == restaurant.user %}
        <a
          href="#"
          data-toggle="modal"
          data-target="#category{{category.id}}"
          class="btn btn-outline-secondary"
          role="button"
          aria-pressed="true"
          >setting</a
        >
        <div
          class="modal fade"
          id="category{{category.id}}"
          tabindex="-1"
          role="dialog"
          aria-labelledby="exampleModalCenterTitle"
          aria-hidden="true"
        >
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">
                  {{category.name}}
                </h5>
                <button
                  type="button"
                  class="close"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <a
                  href="{% url 'category_update' category.id menu.id %}"
                  class="btn btn-info btn-lg"
                  role="button"
                  aria-pressed="true"
                  >Edit Category</a
                >
                <a
                  href="{% url 'category_delete' category.id menu.id %}"
                  class="btn btn-danger btn-lg"
                  role="button"
                  aria-pressed="true"
                  >Delete Category</a
                >
                <a
                  href="{% url 'food_create' category.id menu.id %}"
                  class="btn btn-primary btn-lg"
                  role="button"
                  aria-pressed="true"
                  >Add Food</a
                >
              </div>
              <div class="modal-footer">
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-dismiss="modal"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
      {% endfor %}
    </div>
  </div>

  <div class="col-10">
    {% for category in menu.category_set.all %}
    <div class="food-list">
      <h2 id="{{category.name}}">{{ category.name }}</h2>
      {% for food in category.food_set.all %}
      <div class="card food" style="width: 18rem; margin: 1rem;">
        <img
          src="{{food.food_photo}}"
          class="card-img-top"
          style="max-height: 13rem;"
        />
        <div class="card-body">
          <h5 class="card-title">{{food.name}}</h5>
          <p class="card-text">{{food.description}}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">$ {{food.price}}</li>
        </ul>
        {% if request.user == restaurant.user %}
        <div class="card-body">
          <a href="{% url 'food_update' food.id menu.id %}" class="card-link"
            >Edit</a
          >
          <a href="{% url 'food_delete' food.id menu.id %}" class="card-link"
            >Delete</a
          >
          <a
            href="#"
            data-toggle="modal"
            data-target="#food{{category.name}}{{food.id}}"
            class="card-link"
            role="button"
            aria-pressed="true"
            >Add Photo</a
          >
          <!-- Modal -->
          <div
            class="modal fade"
            id="food{{category.name}}{{food.id}}"
            tabindex="-1"
            role="dialog"
            aria-labelledby="exampleModalCenterTitle"
            aria-hidden="true"
          >
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalCenterTitle">
                    Image Upload
                  </h5>
                  <button
                    type="button"
                    class="close"
                    data-dismiss="modal"
                    aria-label="Close"
                  >
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <form
                    action="{% url 'add_food_photo' food.id menu.id %}"
                    enctype="multipart/form-data"
                    method="POST"
                  >
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="exampleFormControlFile1">Choose Image</label>
                      <input
                        type="file"
                        class="form-control-file"
                        id="exampleFormControlFile1"
                        name="photo-file"
                      />
                    </div>
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-dismiss="modal"
                    >
                      Close
                    </button>
                    <button type="submit" class="btn btn-primary">
                      Upload
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
      {% empty %} {% if request.user == restaurant.user %}
      <a
        href="{% url 'food_create' category.id menu.id %}"
        class="btn btn-outline-info"
        tabindex="-1"
        role="button"
        aria-disabled="true"
        >Add Food</a
      >
      {% endif %} {% endfor %}
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

main/templates/menu/menu_form.html
{% extends 'main/base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Menu</h1>
{% endif %}

<form action="" method="post" class="container">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit!" class="btn btn-primary">
</form>
{% endblock %}